### ISSUE TITLE
Qt5 compatibility

### ISSUE THREAD

**Issue by Laura-K** [BALL-Project/ball#553]
Hello,

I would be interested if an update of the qt5 branch with all the master branch new corrections is done. I tried to merge them myself but now my compilation fail in glrenderer.h. It concerns opengl features, and I'm pretty novice with this API.
Could it be possible ? I would enjoy to have BALL and VIEW for Qt5.

Greetings,
Laura

**Comment by philthiel** [comment]
Hi Laura,

we're currently planning and preparing a new release.
This one will be based on Qt5! As we currently move our whole infrastructure
and additionally prepare a new contrib technology the things take a bit longer ...

However, we hope to release BALL 1.5 in summer.
So don't punish yourself too much with merging Qt5 into master ;)

Best
Philipp



----- Original Message -----
> From: "Laura-K" <notifications@github.com>
> To: "BALL-Project/ball" <ball@noreply.github.com>
> Sent: Wednesday, 17 June, 2015 12:22:26 PM
> Subject: [ball] Qt5 compatibility (#553)
> 
> Hello,
> 
> I would be interested if an update of the qt5 branch with all the
> master branch new corrections is done. I tried to merge them myself
> but now my compilation fail in glrenderer.h. It concerns opengl
> features, and I'm pretty novice with this API.
> Could it be possible ? I would enjoy to have BALL and VIEW for Qt5.
> 
> Greetings,
> Laura
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/BALL-Project/ball/issues/553

-- 

Dr. Philipp Thiel
Diplom-Inform. (Bioinformatics)
Applied Bioinformatics Group
Eberhard Karls Universität Tübingen

Tel:   +49-7071-29-70444
eMail: thiel@informatik.uni-tuebingen.de

**Comment by Laura-K** [comment]
Hi Philipp,

Thank you for your response, this is a good new!
I'm actually in internship for four month, and I plan to have my project using BALL compatible with Qt5 before the end. So I plan to continue to merge the two branches.
Even if I'm novice, would you be intereseted by my work?

Best,
Laura

**Comment by anhi** [comment]
Dear Laura,

we would be very interested in it. There is work on integrating qt5, by the way, but it needs more testing and probably more work. You might want to test the ipython branch that I just pushed to the repository. It is based on the current Qt5 integration and contains some further fixes.

Best,

Andreas

**Comment by Laura-K** [comment]
Hi Andreas,

Thank you for the advice !
I add small improvements of your branch to compile with Visual Studio (you can see them in my fork https://github.com/Laura-K/ball ). This is strange because I needed to rewrite modifications you explicitely did, like put again "GL/" in the includes.

Actually I'm facing three last issues.
glRenderer.C:2450 with 'glTextImage3D' identifier not found. Maybe it's because there'is no glew anymore.
geometricFitDialog.h can't find ui_geometricFitDialog.h
and pythonSettings.h can't find ui_pythonSettings.h
I think it's because I configure the project with -DBALL_HAS_FFTW=OFF and -DBALL_PYTHON_SUPPORT=OFF, the ui_files are not generated (and it's normal) but the compilation should not add these two headers in the project.

I will gradually search how to resolve these three issues in the next days. If you have any ideas, i would be very happy to collaborate with you!

In a few months I will export my project for Mac, so I will be able to give you feedback on this plateform too.

Best,

Laura

**Comment by dstoeckel** [comment]
The "problem" with Qt5 and GLEW is that Qt5 provides its own extension loader. I think the QOpenGLFunctions class is an interface to OpenGL ES instead of the full OpenGL set. Whilest it is nice to use only OpenGL ES compatible functions (easier to port to mobile) glTexImage3D is only available in full OpenGL. For this purpose there are the QOpenGLFunctions_X_Y classes, where X and Y are the version numbers of the required OpenGL release. I think for GLRenderer, QOpenGLFunctions_1_3 should be sufficient.

**Comment by Laura-K** [comment]
Hi,

I put all my work on qt5 (5.4.2 x86 for msvc2012, the version with openGL) and everything works very fine. Except a strange glitch with openGL.
I tested with the minimal VIEW application code : https://gist.github.com/dstoeckel/8bbfc8844f8d78973f0f (I just removed lines 23 and 24 that makes the program crash. Strange, I was sure it worked in the past) and the problem still exist:

With qt5, the scene is first hidden by the right border, instead it should be entirely visible.
The first time I though that it was not displayed at all. Then I realized that I can see it after resizing the window.


![capture](https://cloud.githubusercontent.com/assets/12748164/8933461/372614d4-3543-11e5-86f1-07d37def1f5f.PNG)


If I remove control.setCentralWidget(scene); from the code, I have no way to see the scene.
I'm searching since two days why it occurs. I can move the protein by clicking in the gray zone, that's why I think it is caused by a resizeGL function somewhere, but the GLRenderer class seems not be a child of QGLWidget.

Do you have an idea why it has this strange behavior ?
Thank you very much by advance for your reply.

Best,

Laura

**Comment by dstoeckel** [comment]
This is fixed with current master.
