### ISSUE TITLE
String::insert(const_iterator, initializer_list) fails with GCC

### ISSUE THREAD

**Issue by tkemmer** [BALL-Project/ball#574]
Compilation fails using GCC when `BALL_HAS_STD_STRING_CONST_ITERATOR_FUNCTIONS` is enabled. The GCC implementation of `std::string` (all versions, including 5.3) is still not fully C++11 compatible. While providing some const_iterator functions for `std::string` it still lacks the `std::basic_string::insert(const_iterator, initializer_list<char>)` function, so just checking whether one of the new const_iterator functions is present does not suffice.

**Comment by tkemmer** [comment]
Fixed in qt5_latest branch (8c87dd9294af67b69c2aabe4f062fb405c3745ad).

**Comment by tkemmer** [comment]
Fix merged into master branch (029fd2b9a0365e5926bcb4e2c227533efb356423).

**Comment by shan-weiqiang** [comment]
hi, c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, still has this problem, it seems that std::initializer_list<char> is implicitly converted into std::string, so threre is overload failure problem
do you have some updates on this, or i am missing something so i still have this problem?
